const reveals=document.querySelectorAll('.reveal');new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.16}).observe;const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.16});reveals.forEach(x=>ro.observe(x));
const light=document.querySelector('.water-light');const map={golden:'#cfaa70',blue:'#6e9fa8',candle:'#c68b55',dinner:'#355f66',late:'#243f55',night:'#132f3a',midnight:'#0c1a24'};const so=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){light.style.background=map[e.target.dataset.time]||'#88b6b8';light.style.transform='translate('+(Math.random()*8-4)+'vw,'+(Math.random()*12)+'vh)'}}),{threshold:.45});document.querySelectorAll('[data-time]').forEach(s=>so.observe(s));
const panel=document.getElementById('aiPanel'),launcher=document.getElementById('aiLauncher'),close=document.getElementById('aiClose'),chat=document.getElementById('aiChat'),input=document.getElementById('aiInput');
launcher.onclick=()=>{panel.classList.add('open');panel.setAttribute('aria-hidden','false')};close.onclick=()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true')};
function add(text,type='host'){const d=document.createElement('div');d.className='bubble '+type;d.textContent=text;chat.appendChild(d);chat.scrollTop=chat.scrollHeight}
const flows={
tonight:['Dinner tonight','Lovely. How many guests are joining you? I can take you straight to Mawimbi’s live booking page.'],
celebration:['A celebration','Wonderful. Is it a birthday, anniversary, proposal or another special occasion? For larger plans, I can also direct you to group bookings.'],
group:['Group booking','Mawimbi can host intimate private occasions and larger gatherings of up to 100 guests. I’ll open the group booking page for you.'],
question:['Ask a question','Ask me about parking, opening hours, dress code, seafood, dietary needs or private events.']
};
document.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>{const [q,a]=flows[b.dataset.flow];add(q,'guest');setTimeout(()=>add(a),350);if(b.dataset.flow==='group')setTimeout(()=>window.open('https://www.mawimbirestaurant.com/group-booking/','_blank'),900);if(b.dataset.flow==='tonight')setTimeout(()=>window.open('https://mawimbi-seafood-restaurant.wl.booknbook.com/booking','_blank'),900)});
function respond(){const q=input.value.trim();if(!q)return;add(q,'guest');input.value='';const s=q.toLowerCase();let a='I can help with reservations, the menu, celebrations, location and opening hours.';if(s.includes('parking'))a='Mawimbi is on Kijabe Street, opposite Norfolk Towers. For parking specifics, the restaurant team can confirm the best nearby option at +254 758 956805.';else if(s.includes('hour')||s.includes('open'))a='Mawimbi is open daily from 6am to 11pm.';else if(s.includes('group')||s.includes('party'))a='Mawimbi supports private parties, meetings, birthdays and intimate wedding receptions, with larger gatherings of up to 100 guests.';else if(s.includes('menu')||s.includes('food'))a='The menu includes starters, seafood mains, lobster, sushi, shareable platters such as Poseidon and Tsunami, and desserts.';else if(s.includes('book')||s.includes('reserve')){a='I’ll take you to the live reservation page now.';setTimeout(()=>window.open('https://mawimbi-seafood-restaurant.wl.booknbook.com/booking','_blank'),700)}setTimeout(()=>add(a),350)}document.getElementById('aiSend').onclick=respond;input.addEventListener('keydown',e=>{if(e.key==='Enter')respond()});